config/routes.rb
Rails.application.routes.draw do
  get "/" => "books#top"
  get "books" => "books#index"
  post "books" => "books#create"
  get "books/new" => "books#new"
  get "books/:id" => "books#show", as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  put 'books/:id' => 'books#update'
  delete 'books/:id' => 'books#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
 validates :title,  presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
       flash[:notice] = "Book was successfully created."
       redirect_to @book
    else
      flash.now[:alert] = "can't be blank"
      render :new
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book
    else
      flash.now[:alert] = "can't be blank"
      render("books")
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path(@book)
  end

  def top
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_error_messages.html.erb
<% if model.errors.any? %>
  <div class = "alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
   　　 <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/edit.html.erb
<h2>Editing Book</h2>
<%= form_with model:@book, local:true do |f| %>
  <p class="new-p">Title</p>
  <%= f.text_field :title %>
  <p class="new-p">Body</p>
  <%= f.text_area :body %><br>
  <%= f.submit 'Update Book' %> <br>
  <%= link_to "show", book_path(@book.id) %> |
<%= link_to("Back", "/books") %>
<% end %>

app/views/books/index.html.erb
<h1>Books</h1>
<table>
  <thead>
    <tr>
     <th>Title</th>
     <th>Body</th>
    </tr>
  </thead>
  <tbody>
   <% @books.each do |book| %>
    <tr>
      <td class="tr-td"><span><%= book.title %></span></td>
      <td class="tr-td"><span><%= book.body %></span></td>
      <td class="tr-td"><%= link_to "show", book_path(book.id) %></td>
      <td class="tr-td"><%= link_to "edit", edit_book_path(book) %></td>
      <td class="tr-td"><%= link_to "delete", book_path(book), method: :delete, "data-confirm" => "Are you sure?" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<h2>New book</h2>
<%= form_with model:@book, local:true do |f| %>
  <p class="new-p">Title</p>
  <%= f.text_field :title %>
  <p class="new-p">Body</p>
  <%= f.text_area :body %><br>
  <%= render 'books/error_messages', model: f.object %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/new.html.erb
<h2>New book</h2>
<%= form_with model:@book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %><br>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<table>
  <tbody>
    <tr>
      <td class="tr-td"><h4>Title:</h4></td>
      <td><%= @book.title %></td>
    </tr>
    <tr>
      <td class="tr-td"><h4>Body:</h4></td>
      <td><%= @book.body %></td>
   </tr>
  </tbody>
</table>
<%= link_to "Edit", edit_book_path(@book) %> |
<%= link_to("Back", "/books") %>

app/views/books/top.html.erb
<h1>ようこそ Bookers へ！</h1>
<div class="top_container">
  <p class="top-p">Bookers では、さまざまな書籍に関するあなたの意見や</p><br>
  <p class="top-p">印象を共有し交換することができます</p>
</div>
<%= link_to "start", books_path %>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="flash">
       <%= flash[:notice] %>
      </div>
    <% end %>
     <% if flash[:alert] %>
      <div class="flash">
       <%= flash[:alert] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>